apiVersion: v1
kind: Namespace
metadata: 
  name: bookinfo
---
apiVersion: v1
kind: Namespace
metadata: 
  name: bookinfo-source
---
apiVersion: v1
kind: Namespace
metadata: 
  name: bookinfo-project
---
